### ISSUE TITLE
Version 1.0.6 does not compile 9.2-

### ISSUE THREAD

**Issue by aklaver** [tds-fdw/tds_fdw#43]
Per this thread on pgsql-general:

http://www.postgresql.org/message-id/2A9DC32516465540A0B1D37D25D6EF9A04149BEE4E@FHDP1LUMXC7V12.us.one.verizon.com

aklaver@panda:~/test/tds_fdw> PATH=/usr/local/pgsql92/bin:$PATH make USE_PGXS=1
cp sql/tds_fdw.sql sql/tds_fdw--1.0.6.sql
cp README.md README.tds_fdw.md
gcc -O2 -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -fpic -I./include/ -I. -I. -I/usr/local/pgsql92/include/server -I/usr/local/pgsql92/include/internal -D_GNU_SOURCE   -c -o src/tds_fdw.o src/tds_fdw.c
src/tds_fdw.c:30:33: fatal error: access/htup_details.h: No such file or directory
 #include "access/htup_details.h"
                                 ^
compilation terminated.
<builtin>: recipe for target 'src/tds_fdw.o' failed

**Comment by GeoffMontee** [comment]
Thanks for the bug report!

Our new Jenkins instance only has automated builds for PostgreSQL 9.3+, so it's possible that it's broken on PostgreSQL 9.2. I'll test it out manually.

**Comment by aklaver** [comment]
Well I think the reason for the issue is here:

http://git.postgresql.org/gitweb/?p=postgresql.git;a=history;f=src/include/access/htup_details.h;h=8dd530bd930f1d23f19f36e17112f47c9c498f21;hb=HEAD

2012-08-30 	Alvaro Herrera	Split tuple struct defs from htup.h to htup_details.h

**Comment by GeoffMontee** [comment]
This commit added the dependency on htup_details.h in tds_fdw:

https://github.com/GeoffMontee/tds_fdw/commit/7bb875384734c211733fa1ce4866d890f82e8ec7

I'll try adding some preprocessor macros to include htup.h instead of htup_details.h for 9.2 and below to see if that is enough to fix the problem. Thanks for pointing out the source of the issue.

**Comment by GeoffMontee** [comment]
I just committed a fix that seems to work on PostgreSQL 9.2 and 9.5: https://github.com/GeoffMontee/tds_fdw/commit/fc002c3ebc9b731e17285552e6a3ba90b53f0e35

**Comment by aklaver** [comment]
Confirmed on 9.2.14.

**Comment by juliogonzalez** [comment]
Good news, 9.2 (9.2.14) for both Ubuntu and CentOS is now added to the CI.

@GeoffMontee I moved tds_fdw-build-ng to [tds_fdw-build](https://jenkins-juliogonzalez.rhcloud.com/job/tds_fdw-build/), so we don't get that false errors regarding timeouts for some versions.

Let me know if we need to add more versions and I'll see what I can do.

**Comment by GeoffMontee** [comment]
Awesome! Thanks for making those changes to the Jenkins CI server, @juliogonzalez!
